### ISSUE TITLE
Capitalization

### ISSUE THREAD

**Issue by Johandrex** [MyWarp/MyWarp#142]
Hello,

it'd be amazing if you could add an option allowing us to disable multiple warps with the same letters but different capitalization. Right now players are hijacking other players warps by using the same warp-name with different capitalization, please add this option as fast as possible as it's required to be fixed.

**Comment by TheE** [comment]
Update to the latest devBuild, run it once, then set `settings.caseSensitiveWarpNames` to `false`.
