### ISSUE TITLE
Minor API changes for the Sponge implementation

### ISSUE THREAD

**Issue by TheE** [MyWarp/MyWarp#146]
This ticket is meant to bundle problems or ideas regarding `mywarp-core` that are encountered while writing the sponge implementation. None of these changes block an implementation, but it might be worth to look at these changes before writing yet another implementation.

- [x] Is `BlockFace.NONE` really needed? It might be clearer to just use `null` when a Sign has a different rotation.
- [x] Could `LocalWorld.isFullHight()` be kept for Bukkit only since Sponge users will start with a new database?
- [x] How can Sponge’s `ListService` be used by the core?

**Comment by linkinkov** [comment]
Sponge version will be awesome!
