### ISSUE TITLE
Custom localizations not working on 1.12

### ISSUE THREAD

**Issue by DutchUser** [MyWarp/MyWarp#154]
I recently updated our mywarp to the newest snapshot for 1.12 support.

But what i found out was that he is not longer taking custom message as he did still in the last Beta version.

Is this changed? If yes how do it now work?

I used first lang > me > taylorkelly > mywarp > lang > Commands_nl.properties

**Comment by TheE** [comment]
It is still supposed to work, but maybe the update to Java8 caused some problems. I will look into it.

**Comment by DutchUser** [comment]
I dont use the " MyWarp's official Dutch localization" because i only change the message(s) that players see. Mostly because its a waste of my time to also edit EVERY message of the plugin. And because i dont know how translate every message. My english is not %100 good. I know the basics english. No offens though. Its meaning bad. Thanks for the fast respond.

**Comment by DutchUser** [comment]
Also found a other thing. I was trying to connect it to a MySQL database. But it dont work.

Error log: https://pastebin.com/PPdsD2sg

**Comment by DutchUser** [comment]
Hello.

Do you have a update on this issue? Im kinda waiting on this to be fixed to update our server to fully 1.12

**Comment by TheE** [comment]
I'll try to look into it this weekend. Unfortunately I do not have much time at the moment. :/

**Comment by TheE** [comment]
Found the problem. It is not a technical bug, but rather caused by some internal changes. You can easily fix this yourself by renaming the folders that contains the `Commands_nl.properties`.

Instead of this:

    lang/me/taylorkelly/mywarp/lang/Commands_nl.properties

It needs to look like this:

    lang/io/github/mywarp/mywarp/lang/Commands_nl.properties

I will update the documentation accordingly.
