### ISSUE TITLE
Teleporting while riding donkeys and mules no longer works in 1.12

### ISSUE THREAD

**Issue by Ironic8b498** [MyWarp/MyWarp#156]
I recall on 1.11.2 I was able to warp while on a donkey or mule, in 1.12 I am not able to do so. Is that not possible anymore? Warping while on a horse works fine

**Comment by TheE** [comment]
Apperantly the Spigot team introduced a somewhat braking change with 1.12: Before 1.12 the Horse interface would be implemented by every variant (horses, donkeys, mules). Now this has been replaced by AbstractHorse, Horse only covers regular horses.

I will have to look into how I can adapt to this change while keeping compability with older versions of Minecraft and Bukkit.

**Comment by Ironic8b498** [comment]
thanks
