### ISSUE TITLE
What about remove the UUID in /warp list. [REQUEST]

### ISSUE THREAD

**Issue by DutchUser** [MyWarp/MyWarp#159]
Because i did not understand how to create a "Pull Request" i did it here. Sorry!
(Please dont close the ticket. I have a other small issue. But this have more Prio)

Just look the schreen. Can the UUID format get removed???

https://s11.postimg.org/ee7qwenkz/Knipsel.png

**Edit: I fixed the link.** (Knipsel.png thing)

**Comment by TheE** [comment]
Normally, you will not see UUIDs, but player names. Only if the player name is not available (because this player has not logged so the name is not cached), the UUID is displayed.

This should rarely happen, therefore I am keeping it as it is, sorry.

**Comment by DutchUser** [comment]
As i asked in the first message i ask it again. "**(Please dont close the ticket. I have a other small issue. But this have more Prio)**"

Anyway, How can i remove this. Do every player need te recreate the warps? All the warps are fom our 1.11 version. There is not any UUID as in the picture. There its normal. Only the 1,12 version have the UUID.

**Comment by TheE** [comment]
Ah sorry, my bad. The UUID is displayed instead of the name of the world the warp is located in. It seems like the world is not loaded or does no longer exist.

These warps should not be usable, so - unless you can load the world again - they can be deleted via `/warp delete`.

**Comment by DutchUser** [comment]
Oke. That explained it. Im am going check when i can if this still happen of the worlds are there. 

Second question related to the prefix.(world prefix)

Is there a way to disable this for normal players? That players whitout a specifically permission? I dont se any reason why a player schould see that in /warp list. (Its very Handy in /warp info. Just not in /warp list(My opinion))

**Comment by TheE** [comment]
>Is there a way to disable this for normal players? That players whitout a specifically permission? I dont se any reason why a player schould see that in /warp list. (Its very Handy in /warp info. Just not in /warp list(My opinion))

Not at the moment. When the world name was not shown, several users requested showing it. Ideally this would be configurable, but for now making It configurable is a bit to much work.

(Sorry for answering so late. I do not have much time for MyWarp at the moment.)
