### ISSUE TITLE
Suggestion: add bungeecord bridge

### ISSUE THREAD

**Issue by ArtNRG** [MyWarp/MyWarp#163]
Please add bungeecord version or bungee bridge to allow players making warps and teleporting between bungee servers.

**Comment by TheE** [comment]
While I would love this, the main problem is that MyWarp's design of storing every warp within memory and sync this memory storage to a DB does not work well for multiple servers.

To properly support Bungecord, MyWarp would either need to use a single (hosted) database only and run all queries from all servers against it, or (even more complex) be adapted to work in a decentralized environment by having each server handling its own warps, but allowing for interactions between those servers.

Unfortunately I myself nether have the time to do this, not the motivation (as I stopped playing Minecraft long ago). I will maintain this plugin for as long as possible, but supporting Bungeecord would require a full rewrite which I am unfortunately unable to do.
