### ISSUE TITLE
My screw up, hope you can fix it for me!

### ISSUE THREAD

**Issue by Ironic8b498** [MyWarp/MyWarp#168]
Sunday I was deleting file off server and by mistake T started to remove the survival server folder, I have recovered it back close, but not I get this error when players use their warps.

<The world of the warp 'mine' (identified by e4fe52c8-cf11-4186-a6ad-e3845bba42b9) is not currently loaded on the server. The teleport was aborted.>

**Comment by Ironic8b498** [comment]
somehow in the database my world name was change to e4fe52c8-cf11-4186-a6ad-e3845bba42b9, I have figure out a way to fix them but it will take me days to do it in game via commands, was hoping there is a quick fix to hanging the world name back to world

**Comment by Ironic8b498** [comment]
well I was able to manually update the world by using /warp info <warp> then tp to the cords then update command, took me from time I posted this till now to finish

**Comment by TheE** [comment]
Sorry for not replying earlier, unfortunately I did not have any time for private projects in the last days.
I assume that the world's UUID was somehow changed when you restored it, causing these problems.

I you are ever in such a situation again, you should deactivate MyWarp (e.g. shutdown the server), edit the database directly and reactivate MyWarp.

If the default database H2 is used, its [GUI editor](http://www.h2database.com/html/quickstart.html#h2_console) might become handy. If MySQL or MariaDB is used, you are probably already using tools like phpMyAdmin.

**Comment by Ironic8b498** [comment]
I tried to use that editor but could not figure out how to open a database on my pc and edit it
