### ISSUE TITLE
Suggestion: Allow multiple players to have the same warp name

### ISSUE THREAD

**Issue by Yottazoid** [MyWarp/MyWarp#169]
It would be really nice if more than one player could have the same warp name, for example, "home".
If a player had access to more than one, it would default to their own if they owned one, or could be able to choose between others' with /warp|to [warp-name] <owner>.
This way, players wouldn't have to come up with some other name if "home" was already taken.
xWarp had this feature.

**Comment by TheE** [comment]
I like the idea, but such a change is technically impossible with the way warps are currently managed internally. Also it might tend to brake existing behavior drastically, as it would suddenly require users to remember not only warp names but creators and warps.

If I were to create an entirely new warp plugin today, I would implement such a feature. For MyWarp however unfortunately this is unfeasible.
