### ISSUE TITLE
Warps in a GUI

### ISSUE THREAD

**Issue by Sikatsu** [MyWarp/MyWarp#177]
Would it be possible to implement a GUI? 
So that all public warps show up within a GUI with multiple pages?

Also, I wondered why the MyWarp jar is over 5MB?

**Comment by TheE** [comment]
The general problems with GUIs is that vanilla Minecraft has almost no support for them:
* Custom GUIs almost always require client mods or at least involve using Minecraft code (NMS) directly. This means they need to be updated upon each Minecraft release which is not feasible for me.
* Using inventories is essentially a hack that can go fundamentally wrong and must also be constantly maintained.
* Clickable chat messages are supported by Minecraft, but unfortunately not by Bukkit. The Sponge version will make use of clickable commands for warps, pagination etc. though.
* The same is true for book based GUIs. Minecraft supports adding commands to book text, which could allow for a book of all warps that can be used with a simple click. Afaik Bukkit has no support for this feature, but it should be possible to implement this feature in Sponge.

What kind of GUI do you have in mind?


MyWarp's size of 5MB is the result of bundling required libraries such as H2, JOOQ, FlyWay and Intake. This has however no impact on server performance (quoting [myself](https://dev.bukkit.org/projects/mywarp?comment=457)):
> Once again, file-size and memory usage are two different things. Put short, the JVM finds and loads classes lazily, a class’s byte code is only loaded into memory when the class is first used. The byte code is loaded from the class-path, a location on the file system where the JVM looks for class files. Loaded classes can have multiple instances, witch once more allocate a certain amount of memory each.
>
>To conclude, when speaking about memory usage, the important point is witch classes are loaded by a plugin, and how many instances of this classes are created. For example, the bundled H2 driver is added to the class-path, but never loaded if H2 is not used. Therefore it does not make any significant impact on the server’s memory usage (‚significant‘ because the class-path is indexed when the JVM states to quickly load classes. The index takes some space in the memory, but that is generally way to small to even think about it.)
