### ISSUE TITLE
Allow to specify options for JDBC connections

### ISSUE THREAD

**Issue by bladen** [MyWarp/MyWarp#178]
On startup and when players use warms this message pops up:

> WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.

Can you make it possible to add `?useSSL=false` to the jdbc url?
Thanks!

**Comment by TheE** [comment]
With the latest devBuild you can use the `storage.properties`options in the `config.yml` like so:

```YAML
storage:
  properties:
    useSSL: false
    autoReconnect: true
```
