### ISSUE TITLE
Warp limits not working 

### ISSUE THREAD

**Issue by brr3** [MyWarp/MyWarp#181]
I have read through all the previous topics about this but nothing has helped me resolve the issue. 

I have configued one limit and added that permission to one rank. I use inheritance for my ranks so the one above the one with the permission should inherit that permission. There is no overlapping from what I can tell.

[GroupManagerFiles.zip](https://github.com/MyWarp/MyWarp/files/1917147/GroupManagerFiles.zip)
[MyWarpFiles.zip](https://github.com/MyWarp/MyWarp/files/1917193/MyWarpFiles.zip)

**Comment by TheE** [comment]
I think you have a typo in the permission:

```YAML
  g:essentials_VIP+:
    permissions:
    - mywarp.limits.mod
```

Should be:

```YAML
  g:essentials_VIP+:
    permissions:
    - mywarp.limit.mod
```
(Remove the `s`.)

Let me know if this fixes the problem.

**Comment by brr3** [comment]
Oops, I should have noticed that. It didn't fix it though it seems (I de-opped myself and gave myself VIP but could still place past the limit). I have the default warp limit set to 10 in total (which is the case for VIPs, while anything higher should get 20 total warps using the permission). 

Worth mentioning is I have way more warps than the set limit to begin with (24 warps when the limit is 10). Adding a warp still works in this scenario. Do the limits only work if you are below the limit to begin with, or does the plugin check if the amount of warps is larger or equal to the set limit?

**Comment by brr3** [comment]
Bump. Any luck figuring this out?

**Comment by TheE** [comment]
Sorry for not answering. I will have to test this with GroupManager by myself, as the config looks fine.

I promise I will do this by 20/05/18 - unfortunately I have hardly any time for non work related stuff atm.

**Comment by TheE** [comment]
So, I just tested your files in GroupManager on my own test server. Unfortunately, I cannot reproduce your problem, everything works as expected.

You said above that you promoted yourself to `vip`. But reading from your files, players need to have `VIP+` in order to have the `mod` limit. Could you please test, if it still does not work if you (1) use `mywarp.limit.mod` (no plural as said above) and (2) you are in the `VIP+` group?

**Comment by brr3** [comment]
I changed my GroupManager config to inherit the group.yml and users.yml files from the main world. The warp limits now seem to work in that main world, but nowhere else. Tried specifying each world under "affectedWorlds" in the MyWarp config but to no avail. Will keep experimenting!

**Comment by brr3** [comment]
After more testing it seems like as soon as I make myself VIP+ the limit stops working in the main world, and doesn't work anywhere else just like when I am VIP. If I remove the permission `mywarp.limit.mod` the limit works for me when I am VIP+ in the main world, since it is then using the default limit. So the configured limit is not working, and the default limit only works in the main world.

**Comment by TheE** [comment]
Thank you for this update. This is an extremely strange behaviour.

What strikes me most is that the default limit only works in the main world. Technically, the default limit is a fallback: It is always used as a fallback if other limits or disobey permissions are not present. If it does not work, something must block it.

Could you test  if it works on a different world than main when you explicitly **negate** the following permissions on this world for yourself (non-op)?
```
mywarp.limit.disobey.[WORLDNAME].total
mywarp.limit.disobey.[WORLDNAME].public
mywarp.limit.disobey.[WORLDNAME].private
mywarp.limit.disobey.[WORLDNAME].*
mywarp.limit.disobey.*
```
The world name is case sensitive.

Also, if you are not making this test on a public server, could you maybe give it a short try using another permission plugin?

**Comment by brr3** [comment]
Tried using LuckPerms, but contrary to the name of the plugin I did not have any luck. Used the migration command to move everything over from GroupManager, with no errors. The VIP rank has all the commands as it did with GroupManager so I assume it worked. The issue with MyWarp persists.

**Comment by TheE** [comment]
I just tested it again but without luck: I cannot reproduce your issue using [this](https://gist.github.com/TheE/6efe09152502b97edc7a9c2abac53e8d) file.

- I used the latest [devBuild](https://mywarp.github.io/builds.html). Are you using it, too?
- I used the last version of CraftBukkit for 1.12.2 (`CraftBukkit version git-Bukkit-2b93d83 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT`). Are you using it, too?
- I used GroupManager `2.0.1-b332`. Are you using it, too?
- Are you absolutely sure that you are no longer OP when testing?

**Comment by brr3** [comment]
Sorry, I don't mean to waste your time and I should have done way more testing than I have done thus far. I really appreciate your help in trying to resolve this.

When you did your testing, did you try going over the limit in several worlds? Because that seems to be the problem for me.

I tried removing all warps and reset the config again, and I found that warps are limited on a "per world" basis and not globally. I set two warps in one world and two in another, with the global limit at just two, and as soon as I tried to place the third warp in both worlds I got the "too many warps" message. I did my testing with the permissions negated as you advised me to do above, but that did not make a difference. I am definitely not OP when doing the testing as I always check my commands with /help and they are always correct for VIP, plus the fact the game tells me I am no longer OP.

In this round of testing I used the latest Spigot build for 1.13.1 and your latest release of MyWarp for 1.13.1. I use "EssentialsXGroupManager 2.0.1-b332", but I couldn't find where I got it from. I inherit the users.yml and groups.yml files from the main world to every other world to make things easier. I will add screenshots to make the steps I took in-game extra clear. The first three are from one world, the last two from the other world.

![2018-09-05_20 33 13](https://user-images.githubusercontent.com/36078418/45114876-7eefa480-b14e-11e8-99e9-fe222f21ae1e.png)
![2018-09-05_20 33 35](https://user-images.githubusercontent.com/36078418/45114888-8747df80-b14e-11e8-9aef-f4b543392c76.png)
![2018-09-05_20 33 58](https://user-images.githubusercontent.com/36078418/45114894-8ca52a00-b14e-11e8-9198-68680f5dc3c5.png)
![2018-09-05_20 34 59](https://user-images.githubusercontent.com/36078418/45114897-8e6eed80-b14e-11e8-899a-3bdfd73db75c.png)
![2018-09-05_20 35 48](https://user-images.githubusercontent.com/36078418/45114899-8fa01a80-b14e-11e8-94da-a776f3a1f172.png)

**Comment by brr3** [comment]
Here is my GroupManager config.yml, globalgroups.yml, users.yml and MyWarp config.yml.

[GroupManager.zip](https://github.com/MyWarp/MyWarp/files/2354234/GroupManager.zip)
[MyWarp.zip](https://github.com/MyWarp/MyWarp/files/2354235/MyWarp.zip)

Delete any files I have given to you earlier and use these if you decide to test again. These are the ones I used for my testing above, without the negated permissions for GroupManager as they didn't seem to have an affect.

**Comment by brr3** [comment]
Tested with two fresh 1.13.1 worlds and the limit is still applied on a "per world" basis.

**Comment by TheE** [comment]
> When you did your testing, did you try going over the limit in several worlds? Because that seems to be the problem for me.

This finally did the trick, I was able to reproduce the problem. A fix may take two or three weeks as I will probably just rewrite the handling of limits, because the current version is rather ugly and a hell to maintain...

Thanks for doing all of this tests!

**Comment by TheE** [comment]
Could you test if the last [devBuild](https://mywarp.github.io/builds.html) (#1627) solves the issue?

**Comment by brr3** [comment]
It works, thank you!!
