### ISSUE TITLE
Signs - case sensitive warp names

### ISSUE THREAD

**Issue by ArtNRG** [MyWarp/MyWarp#182]
Warp names on signs are case sensitive even when settings.caseSensitiveWarpNames config option is false.

**Comment by TheE** [comment]
If I remember correctly, MyWarp attempts to set the correct case of a warp name on the sign upon creation.

Could you briefly describe, why this behaviour is still problematic? Was the warp deleted and than recreated using a different case or...?

**Comment by ArtNRG** [comment]
Seems like the warp is creating like it was typed without recreating. Players can use /warp WarpName typed in any case, but if they want to add the warp sign, they must use the valid case as listed in /warp info WarpName. 

Paperspigot build 1415 (MC: 1.12.2)
Plugin version 3.0-SNAPSHOT+jenkins-b192.git-91cdc14a6b
config.yml https://pastebin.com/raw/tGp6QWxB

**Comment by TheE** [comment]
Should be fixed in the latest devBuild.

However, please note that if there are (for some reason) two warps with the same name in different case (e.g. `TEST` and `test`) signs will not work for either of them, regardless of the sign's text.
