### ISSUE TITLE
Update for Bukkit 1.13`s Materials

### ISSUE THREAD

**Issue by TheE** [MyWarp/MyWarp#189]
Bukit 1.13 introduces several braking changes, including renamed Materials. `MaterialInfo` has to be adapted for these changes, possibly by making it `VersionSupportable`.

**Comment by Ironic8b498** [comment]
Keep up the good work, the 192 build will work in 1.13, we all can use till you get it working correctly

**Comment by TheE** [comment]
Thank you. :)

[Build 1614](https://mywarp.github.io/builds/d9992c7.html) should allow MyWarp to run on 1.13, as it has been adapted for the renamed Materials. Let me know if there are any issues that I have not yet found.
