### ISSUE TITLE
MySQL storage

### ISSUE THREAD

**Issue by ArtNRG** [MyWarp/MyWarp#192]
### Question
How to set up the MySQL storage?
I use these settings:
https://pastebin.com/raw/a9aiE0eF
And the plugin can't be loaded. Console error: https://pastebin.com/raw/7p3iDbDP
### Additional context
The database is created for mywarp and it is empty. The same config worked ok with build 3.0-SNAPSHOT+jenkins-b192.git-91cdc14a6b, now I trying to setup 3.0-SNAPSHOT+travis-b1627.git-c4a48e16bb.
I also tried to type schema, user, password etc without quotes, all the same.

**Comment by TheE** [comment]
Should be fixed as of ba6568ab23205c6498b972717c19dbc0bd3d7f64. However, due to GitHub's current side problems, the devBuild is not available currently. I will update this issue once a working devBuild is available.

**Comment by TheE** [comment]
A (hopefully) working devBuild can be found [here](https://mywarp.github.io/builds/ba6568a.html). :)
