### ISSUE TITLE
Converting warps from h2 to MySQL

### ISSUE THREAD

**Issue by q220** [MyWarp/MyWarp#193]
### Question
Ive been using the h2 db engine supplied by MyWarp by default for some time. However I want to switch to MySQL because its easier to write scripts for and I find it easier over SSH to work on MySQL.

The MySQL database is setup just fine, and MyWarp made the tables that it needs on the first run. When trying to do the conversion with the `/warp import current|curr connectionconfiguration` command I keep getting errors. I'm not quite sure how to use this. It also seems to require 3 extra values to work.

The `connectionconfiguration`, I suppose this is the old database, so in the case of a h2 database, this should be `jdbc:h2:/path/to/plugins/MyWarp/warps` pointing to the warps.h2.db file? `current` used the engine declared in the config.yml? What about the additional required parameters, does that need to be the password, username and table for the old database?

### Additional context
The error I'm getting is:

> [Sat, 17. Nov 2018 08:20:29 CET INFO] Could not establish database connection in order to import warps: io.github.mywarp.mywarp.internal.jooq.exception.DataAccessException: SQL [select "mywarp"."warp"."name", "c"."uuid", "mywarp"."warp"."type", "mywarp"."warp"."x", "mywarp"."warp"."y", "mywarp"."warp"."z", "mywarp"."warp"."yaw", "mywarp"."warp"."pitch", "mywarp"."world"."uuid", "mywarp"."warp"."creation_date", "mywarp"."warp"."visits", "mywarp"."warp"."welcome_message", "mywarp"."player"."uuid", "mywarp"."group"."name" from "mywarp"."warp" join "mywarp"."world" on "mywarp"."warp"."world_id" = "mywarp"."world"."world_id" join "mywarp"."player" "c" on "mywarp"."warp"."player_id" = "c"."player_id" left outer join "mywarp"."warp_player_map" on "mywarp"."warp_player_map"."warp_id" = "mywarp"."warp"."warp_id" left outer join "mywarp"."player" on "mywarp"."warp_player_map"."player_id" = "mywarp"."player"."player_id" left outer join "mywarp"."warp_group_map" on "mywarp"."warp_group_map"."warp_id" = "mywarp"."warp"."warp_id" left outer join "mywarp"."group" on "mywarp"."warp_group_map"."group_id" = "mywarp"."group"."group_id"]; (Message 90079 not found); SQL statement:
select "mywarp"."warp"."name", "c"."uuid", "mywarp"."warp"."type", "mywarp"."warp"."x", "mywarp"."warp"."y", "mywarp"."warp"."z", "mywarp"."warp"."yaw", "mywarp"."warp"."pitch", "mywarp"."world"."uuid", "mywarp"."warp"."creation_date", "mywarp"."warp"."visits", "mywarp"."warp"."welcome_message", "mywarp"."player"."uuid", "mywarp"."group"."name" from "mywarp"."warp" join "mywarp"."world" on "mywarp"."warp"."world_id" = "mywarp"."world"."world_id" join "mywarp"."player" "c" on "mywarp"."warp"."player_id" = "c"."player_id" left outer join "mywarp"."warp_player_map" on "mywarp"."warp_player_map"."warp_id" = "mywarp"."warp"."warp_id" left outer join "mywarp"."player" on "mywarp"."warp_player_map"."player_id" = "mywarp"."player"."player_id" left outer join "mywarp"."warp_group_map" on "mywarp"."warp_group_map"."warp_id" = "mywarp"."warp"."warp_id" left outer join "mywarp"."group" on "mywarp"."warp_group_map"."group_id" = "mywarp"."group"."group_id" -176]

**Comment by TheE** [comment]
You also need to specify username and password of the database, as well as the name of the database schema used by MyWarp like so:
````
/mw import current jdbc:h2://my_user:my_password@./plugins/MyWarp/warps//schema
````
If you are using the defaults, the following should work:
````
/mw import current jdbc:h2://mywarp:mywarp@./plugins/MyWarp/warps//mywarp
````

**Comment by q220** [comment]
I'm using the defaults for the h2 database, so when I tried the command, it give me the following:

`>mw import current jdbc:h2://mywarp:mywarp@./plugins/MyWarp/warps//mywarp
[13:27:37 INFO]: /mw import current connectionconfiguration
Too few arguments! No value found for parameter 'connectionconfiguration'
`
However our dev pointed out the following command works (and it does!)
`/warp import current jdbc:h2:./plugins/MyWarp/warps mywarp mywarp mywarp`
