### ISSUE TITLE
Warp safety 1.13 blocks

### ISSUE THREAD

**Issue by martijnpu** [MyWarp/MyWarp#196]
### Description of the Problem
```
Warps on 1.13 blocks are marked as unsafety
```

### Steps to Reproduce
```
Set a warp on top of a 1.13 block an warp to it.
http://prntscr.com/m30j47
http://prntscr.com/m30jaf
```

### Log Output
```
nothing special
```

### Affected Version
* MyWarp: `3.0+travis-b1749.git-c3cbe614dd`
* Minecraft and Bukkit Implementation: `1.13.2-R0.1-SNAPSHOT`

### Additional context
```
None
```

**Comment by TheE** [comment]
Thank you for bringing this issue to my attention. Could you please test if the latest devBuild fixes the problem?
