### ISSUE TITLE
Only english translation packed to jar

### ISSUE THREAD

**Issue by SHADOWDANCH** [MyWarp/MyWarp#198]
### Description of the Problem
In last plugin jar from dev.bukkit.org packed only english translation.

### Steps to Reproduce
Open `mywarp-bukkit-3.0-all.jar` as archive and go to `io\github\mywarp\mywarp\lang` there only files with `_en` suffix and just without suffixes.

### Affected Version
* MyWarp: `3.0+travis-b1749.git-c3cbe614dd`
* Minecraft and Bukkit Implementation: `This server is running CraftBukkit version git-Spigot-eb3d921-2b93d83 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)`

### Additional context
Here https://github.com/MyWarp/MyWarp/issues/197#issuecomment-452882350 in archive not russian translation it's english.

**Comment by TheE** [comment]
I fixed the problem with 32897eb. The latest [development build](https://mywarp.github.io/builds/32897eb.html) again contains all translations.

I will release a new version on BukkitDev soon.
