### ISSUE TITLE
Can my plugin hook into yours with CustomEvents

### ISSUE THREAD

**Issue by andrew121410** [MyWarp/MyWarp#203]
Can you make a custom event when a player warps too a warp so I can use that custom event in my plugin.

I just need too get the player location before the player warps too the warp.

**Comment by TheE** [comment]
Why have you closed this issue? Did you find another way to do what you wanted to do?

For now, MyWarp only includes an internal event that fires when a warp is updated (e.g. the warp's visit counter). This event does not allow to get the player or her old location, but I could easily add this if needed...
