### ISSUE TITLE
Add GriefProtection support

### ISSUE THREAD

**Issue by CircusCow** [MyWarp/MyWarp#206]
Add support for GriefProtection regions. I don't want people to be able to create public warps in other people's regions.

**Comment by TheE** [comment]
I have not used GriefProtection myself, is there maybe a feature to configure which commands are allowed or disallowed within certain regions? If yes, you could simply disallow the commands `mw create` and `mw set` (an their aliases) within regions not owned by the player - this way I solved the issue with WorldGuard on my own server.

If there isn't such a feature, it might be worth asking GriefProtection to implement it as I think this will be useful in a couple of contexts and not just for MyWarp.

**Comment by TheE** [comment]
You might want to look into [GriefPrevention Flags](https://www.spigotmc.org/resources/griefprevention-flags.55773/). The flag `[CommandBlackList](https://github.com/ShaneBeee/GriefPreventionFlags/wiki/Flags#commandblacklist)` should do exactly what you want.

**Comment by CircusCow** [comment]
> You might want to look into [GriefPrevention Flags](https://www.spigotmc.org/resources/griefprevention-flags.55773/). The flag [`CommandBlackList`](https://github.com/ShaneBeee/GriefPreventionFlags/wiki/Flags#commandblacklist) should do exactly what you want.

Dude, thanks so much. You're a legend

**Comment by CircusCow** [comment]
So after looking into it more, it also removes the ability for a player to create a public warp inside their own claim which is an issue

**Comment by CircusCow** [comment]
The only issue is that players that own the land aren't able to create warps either.

**Comment by TheE** [comment]
Sorry for not replying earlier.

In my view, this is something that should be covered by GriefPrevention itself (or an add-on for it). Other region plugins, like WorldGuard, come with an option to allow or disallow certain commands within certain regions. Implementing this is way easier than it is for me to depend on GriefPrevention to implement such a feature in MyWarp.
