### ISSUE TITLE
Importing from H2

### ISSUE THREAD

**Issue by Ironic8b498** [MyWarp/MyWarp#208]
Having trouble running the import command to move warps from H2 db to mv db. 
/warp import current jdbc:h2:/plugins/MyWarp/warps//mywarp

**Comment by TheE** [comment]
When importing from H2, usually you also have to specify username and password. If you are using MyWarp's defaults, the following should work:

    jdbc:h2://mywarp:mywarp@./plugins/MyWarp/warps//mywarp

**Comment by Ironic8b498** [comment]
when I run this command
/warp import current jdbc:h2://mywarp:mywarp@./plugins/MyWarp/warps//mywarp
I get this error
https://paste.helpch.at/hadufudugu.md

If I run this command it tells me "Please choose a sub-command.
/warp import [-t:table-to-import] legacy  legacy jdbc:h2://mywarp:mywarp@./plugins/MyWarp/warps//mywarp

**Comment by Ironic8b498** [comment]
I was able to get my old H2 db to work, but on fresh install of myWarp on 1.14 the file is a warps.mv.db. I guess I didn't ask my question right maybe. I want to move my warps from the H2 db to the new mv db, is that possible?

**Comment by TheE** [comment]
I understand. Technically, both the new `mv.db` and the old `h2.db` are H2 databases. There is no technical need ti import your old warps in the new database, you can use the old one without any downsides.

With that being said, you should be able to import them like so:

1. Rename your old database to `old.h2.db` and place it in MyWarp's plugin folder,
2. Start your server using the default configuration,
3. Issue the following command in the server console:

````
mw import current jdbc:h2://mywarp:mywarp@./plugins/MyWarp/old//mywarp
````

**Comment by Ironic8b498** [comment]
I tried to do that on spigot 1.14 and got this error.
https://paste.helpch.at/gowedotada.md

I also tried on 1.13.2 and got this error
https://paste.helpch.at/atalucoyec.md

**Comment by TheE** [comment]
H2 cannot create its trace file in the current directory. Most likely this means that the path given in the import command is somehow wrong. You could try the following:

1. Open MyWarp's `config.yml` and search for the value of `store.url`.
2. Copy the part that comes after `h2:` until `/warps`.<br />For example, if the full  value is `jdbc:h2:/Users/mc/server/plugins/MyWarp/warps`, Copy only `/Users/mc/server/plugins/MyWarp`.
3. Issue the rolling command, replacing `XXX` with the path you just copied:
````
mw import current jdbc:h2://mywarp:mywarp@##/old//mywarp
````

**Comment by Ironic8b498** [comment]
looks like I'm getting closer

[16:05:26] [Server thread/INFO]: Could not establish database connection in order to import warps: Connection failed due to an SQLException. Is the configuration valid?
