### ISSUE TITLE
Redstone and Pressure Plates blocked

### ISSUE THREAD

**Issue by kaiarne** [MyWarp/MyWarp#212]
### Description of the Problem
Redstone and elements like pressure plates don't work with MyWarp loaded.

### Steps to Reproduce
Plain Spigot with only MyWarp loaded. 
- Stepping on a pressure plate connected to a door.
- using a switch to turn on a redstone torch etc etc.

### Log Output
nothing specific

### Affected Version
* MyWarp: 
MyWarp v3.0-SNAPSHOT+travis-b1663.git-e6d93f3d0f and
MyWarp v3.0.2-SNAPSHOT+unknown-b0.git-61ceac2b4e

* CraftBukkit version:
git-Spigot-03bd4b0-342194e (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)
Latest Spigot 1.13.2 is also affected when using ViaVersion 2.10.

### Additional context

Took me a while to find out that it's MyWarp causing this. Original suspect was Worldedit, which earlier versions seem to have had a similar problem: https://www.reddit.com/r/Minecraft/comments/bi28qe/worldedit_alternative_for_114/

**Comment by TheE** [comment]
Thanks for reporting. The issue should be fixed in the latest development build.
