### ISSUE TITLE
Random sort of warps

### ISSUE THREAD

**Issue by baticag** [MyWarp/MyWarp#213]
### Is your feature request related to a problem? Please describe
My players gain advantage by making warps that are named with start letters like "a..." "!...".

### Describe the solution you'd like
Randomized warp list in command output

### Describe alternatives you've considered
/

### Additional context
/

**Comment by jovanmanic** [comment]
Nice suggestion... Like this they put exclamation mark as much as they can, here is photo... http://prntscr.com/o3501r

**Comment by TheE** [comment]
Could you briefly explain why this is an advantage for players? I understand that this may be irritating, but normally the list command is used when searching for a particular warp - in this case, a randomized order would be far from ideal.

(Sorry for not replying earlier, I do not have much time for MyWarp at the moment.)

**Comment by baticag** [comment]
@jovanmanic explained it partially. We use player warps on our server as a way for other players to find shops. Players wanna be high on that list of warps, so more players visit their shops. This is a big advantage.

**Comment by jovanmanic** [comment]
When they wanna go to specific warp, they already know the name of the warp beacuse they saw it somewhere. When they want to search, they will search no matter how it is sorted, but like this we are creating/making much more beautiful list without unnecessary simbols and equaly visited warps.

**Comment by TheE** [comment]
Added. using the last development version, just set `settings.defaultListSorting` to `random` in the configuration file.

Sorry it took so long.
