### ISSUE TITLE
[QUESTION] Warps wiped

### ISSUE THREAD

**Issue by willc5** [MyWarp/MyWarp#215]
Last time I transferred my Minecraft server to another host, all the created warps completely wiped. How can I avoid this next time? I am transferring to another server soon.

**Comment by TheE** [comment]
Sorry for not answering earlier.

As long as you also migrate your existing worlds to another server hoster, you can easily transfer your existing warps, too. How you do this depends on whether you use MySQl or H2:

#### Using H2

Transfer MyWarp's entier plugin directory (*plugins/MyWarp`) to your new sever. This directory contains the H2 database with all warps.

#### Using MySQL

Backup MyWarp's MySQL database using a tool like phpmyadmin (this is normally provided by your hoster). On your new server, first restore MyWarp's database from the backup, then configure MyWarp to use it by entering the connection details in the `config.yml`.

If you do not have direct access to your MySQL database and cannot back it up directly, you should probably switch to H2 on your old server, import the warps from MySQL into H2 and than migrate to your new hoster using the H2 method described above.

See [here](https://github.com/MyWarp/MyWarp/wiki/Warp-Storage#migrating) for more information.
