### ISSUE TITLE
[Bug] Plugin not loading on a 1.15.2 server

### ISSUE THREAD

**Issue by pjt0720** [MyWarp/MyWarp#234]
### Description of the Problem
I downloaded MyWarp for both 1.15 and the 1.15.2 snapshot version. I tried both them separately and my command logs was showing that MyWarp was failing to load each time. 

### Steps to Reproduce
Download the Snapshot version for 1.15.2 and try to run on a Minecraft server.

### Log Output
https://pastebin.com/HsdceNgN

### Affected Version
* MyWarp: mywarp-bukkit-3.1.1-SNAPSHOT-all
* Minecraft and Bukkit Implementation: 1.15.2

**Comment by TheE** [comment]
Does it work when you use a new database?

If so, most likely your existing database file is corrupted, see [here](https://github.com/h2database/h2database/issues/2078). It is possible that problematic file was tolerated by by older versions of H2, but - after updating the bundled H2 - is no longer usable.

In this case, you can try to export the database using H2's script interface and recreate it from this export (again, using H2' script interface) as described [here](https://h2database.com/html/tutorial.html#upgrade_backup_restore). If you need help, you can also send me the database file and I see what I can do.

**Comment by pjt0720** [comment]
Will doing this delete the warps that players have already created? That is the only thing that I am fearful of is deleting already created warps that players have made. 

I am guessing trying to convert the file is the only way to try and save the warps?

Thanks,
pjt0720.

**Comment by TheE** [comment]
No, you will (most likely) not lose any data.

The idea is to load the corrupted database using an older version of H2 (which still tolerates the corruption) and export all data as `.sql`. Then, create a new database using the newest version of H2 and reimport all data from the `.sql`.

The process is outlined in H2's [docs](https://h2database.com/html/tutorial.html#upgrade_backup_restore). However, if you prefer, you can send me the database (`warps.h2.db` from MyWarp's plugin directory) and I will do the conversion for you.

You might be able to use an older development build of MyWarp, but the problem will just reappear whenever you update MyWarp and H2.

**Comment by pjt0720** [comment]
Here is a link to download the database file.

https://filebin.net/j5r2kdwnsj5x2oj8

**Comment by TheE** [comment]
Right, `warps.h2.db` are created by an even older version of H2, `warps.mv.db` is correct.

[Here](https://filebin.net/dssihm88jgm2us3m) is the link to the recreated file. It loads fine in H2, so hopefully it loads in Minecraft, too.

Please let me know if your problem is fixed.
