### ISSUE TITLE
[FEATURE] Quests integration

### ISSUE THREAD

**Issue by Corazun** [MyWarp/MyWarp#235]
Hello, the plugin is very nice and I thought it could be really cool to have a Quests integration to allow players to teleport only if they have a sufficient amount of quest points.

**Comment by TheE** [comment]
You are taking about PikaMug's [Quest plugin](https://www.spigotmc.org/resources/quests.3711/) plugin, right?

As far as I understand their [API documentation](https://github.com/PikaMug/Quests/wiki/Master-%E2%80%90-Custom-Quest-API), an integration based on the player's quest points is not possible. The API allows to create custom quests (requirements, rewards and objectives), but not to get a player's quest points.

The only integration possible would be to implement warp access as a reward for completing a user-defined quest. This is not what you were asking for; furthermore, you could easily implement this yourself using permissions (assign the permission 'mywarp.warp.to' to players who complete a quest or use [group invites](https://github.com/MyWarp/MyWarp/wiki/Command-Reference#social-commands)).

So, for now, I feat that integrating MyWarp with Quests is impossible. However, feel free to reopen the issue if you have other ideas on how to integrate both.
