### ISSUE TITLE
[Bug] Inviting Players to private warps throws an 'internal error'

### ISSUE THREAD

**Issue by Namoop** [MyWarp/MyWarp#237]
### Description of the Problem
Inviting Players to private warps throws "an internal error."

### Steps to Reproduce
1. Create a private warp
2. Attempt to invite a player

### Log Output

none

### Affected Version
* MyWarp: ` 3.1 `
* Minecraft and Bukkit Implementation: `Spigot-1339488-1816850 (MC:1.15.2) `

### Additional context
None

**Comment by TheE** [comment]
There should be an error logged to the server console. Could you send me the log so that I can investigate what goes wrong?

**Comment by Namoop** [comment]
sorry, i fixed it myself. i was trying to invite a player that was offline. it works fine for online players

**Comment by TheE** [comment]
Sorry for not answering earlier. 

I cannot reproduce this. Running 1.16.3 and the lates development build of MyWarp, inviting a player who is offline to a private war works as expected. Perhaps Mojang's server were not reachable to lookup the player's UUID?

I am closing this ticket now, but please reopen it if you encounter the bug again.
