### ISSUE TITLE
[Bug] Unable to initialize warp storage / SQL tables

### ISSUE THREAD

**Issue by CodeByCam** [MyWarp/MyWarp#238]
### Description of the Problem
Unable to initialize SQL tables.

### Steps to Reproduce
Error on server start.

### Log Output
https://hasteb.in/isagejez.cs

### Affected Version
* MyWarp: `MyWarp version 3.1+Travis-b1815.git-77239c4f28 `
* Minecraft and Bukkit Implementation: `This server is running Tuinity version git-Tuinity-"6316c97" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT) `

### Additional context
Firstly, this _could_ be because I'm running Tuinity (which uses Java 11). 
I'm updating my server to 1.15.2 from 1.14.4, my production server doesn't have this issue, however my Dev server does. The error message does state to upgrade MariaDB, but this issue isn't present on my production server which is using the same MariaDB version.
My production server is running:
* MyWarp: `MyWarp version 3.0.2-SNAPSHOT+Travis-b1808.git-c5635e98ab `
* Minecraft and Bukkit Implementation: `This server is running Paper version git-Paper-237 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)`

MySQL settings are:
```
storage:
  schema: dev
  user: dev
  password: -
  properties: []
  url: jdbc:mysql://localhost/dev
```

Please let me know if you require anything else!
Cheers

**Comment by TheE** [comment]
I dopt that this is caused by Tuinity. The error is thrown by Flyway, a library MyWarp uses to manage its SQL-tables. What version of MariaDB are you using?

MyWarp 3.0.2 still bundles an older version of Flyway. Could you test it with the [last development](https://mywarp.github.io/builds/) build? It bundles a newer version of Flyway that might fix the issue.

**Comment by CodeByCam** [comment]
Hey, 
Sorry for my delay in getting back to you. 

I just tried to run the development build you recommended and still [got the same error](https://hasteb.in/dosuleki.cs).

I am 3 versions behind the latest stable release of MariaDB:
`Ver 15.1 Distrib 10.1.44-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2` 
I could upgrade it to the latest, but it just means there would be a lot of downtime for my server because of all the databases that would need backing up prior.

**Comment by TheE** [comment]
MariaDB 10.1 is no longer supported by the free version of Flyway, see [here](https://flywaydb.org/documentation/database/mariadb). So you either need to update to a newer version or switch MyWarp to use H2.
