### ISSUE TITLE
[QUESTION] Only ops can use the warp commands?

### ISSUE THREAD

**Issue by Aguee** [MyWarp/MyWarp#239]

**Comment by Aguee** [comment]
When normal players (without op) try to use the warps, a message about no permission comes up. How do I fix this?

**Comment by TheE** [comment]
MyWarp does not grant any permissions to non-OPs by default. You have to manually assign the `mywarp.cmd.to` permission to your players to allow them to use the `/to` command.

See the [command reference](https://github.com/MyWarp/MyWarp/wiki/Command-Reference#usage-commands) for all commands and permissions.
