### ISSUE TITLE
how do I change the mywarp.cmd.to permission and set it to all?[QUESTION]

### ISSUE THREAD

**Issue by Aguee** [MyWarp/MyWarp#241]

**Comment by TheE** [comment]
You need a permissions plugin such as [LuckyPerms](https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140) to set the permission (just like any other permission). Also, please have a look at the article on [public vs. private warps](https://github.com/MyWarp/MyWarp/wiki/Introduction#public-and-private-warps) to understand how MyWarp works.

If you have more questions, please comment on **this issue** and **do not** open separated issues. You can comment on closed issues. Thanks.
