### ISSUE TITLE
[Bug] Storage problem after update

### ISSUE THREAD

**Issue by ArtNRG** [MyWarp/MyWarp#242]
### Description of the Problem
After updating the plugin the warp storage fails to initialize.
After downgrading back the warp storage fails to initialize again. 
So I can't get my warps data using both the new and old versions of the plugin.

MyWarp v3.0.1-SNAPSHOT+travis-b1772.git-32897eb313
MyWarp v3.1.1-SNAPSHOT+Travis-b1843.git-8c61372fdd

### Steps to Reproduce
Try to load my db file [warpsDB.zip](https://github.com/MyWarp/MyWarp/files/4418334/warpsDB.zip)

schema: mywarp
user: mywarp
password: mywarp
properties: []

### Log Output
build 1843: https://pastebin.com/raw/jNnU1SqE
build 1772 after downgrading: https://pastebin.com/raw/38dZyF7v

### Affected Version
MyWarp v3.0.1-SNAPSHOT+travis-b1772.git-32897eb313
MyWarp v3.1.1-SNAPSHOT+Travis-b1843.git-8c61372fdd
Tuinity version git-Tuinity-"c2ad42c" (MC: 1.15.2)

**Comment by TheE** [comment]
See #234. Your existing database file is corrupted, see h2database/h2database#2078. The corruption was tolerated by the older version of H2 bundled by MyWarp 3.0.1, but is no longer compatible with the newer version of H2 bundled by MyWarp 3.1.1.

Fixing the corrupted database is relatively easy:
1. Load the corrupted database using H2 1.4.199 (which still tolerates the corruption).
2. Export all data to an SQL script using the using the Script Tool.
3. Import the SQL script using H2 1.4.200.

The process is outlined in H2's [docs](https://h2database.com/html/tutorial.html#upgrade_backup_restore).

I just did exactly this with your database. You can download the restored version here: [warps-restored.mv.db.zip](https://github.com/MyWarp/MyWarp/files/4420054/warps-restored.mv.db.zip).

Please let me know if it works.

**Comment by ArtNRG** [comment]
I downloaded the file and it is OK, thank you! Now I will use a MySQL database to avoid the same problems in the future.
