### ISSUE TITLE
[Bug] No suitable driver found for Mariadb

### ISSUE THREAD

**Issue by ArtNRG** [MyWarp/MyWarp#243]
### Description of the Problem
I'm trying to set up the Mariadb warp storage and get the error "No suitable driver found for Mariadb".

### Steps to Reproduce
Try to use any MariaDB database

config:
schema: mywarp
user: user
password: pass
properties:
autoReconnect: true
useSSL: false
url: jdbc:mariadb://localhost/

### Log Output
https://pastebin.com/raw/qHaUx6fB

### Affected Version
MyWarp version 3.1.1-SNAPSHOT+Travis-b1842.git-d8bab4f38c
Paper-155 (MC: 1.15.2)
10.4.12-MariaDB MariaDB Server
CentOS Linux release 7.7.1908 (Core)

UPD: tested with v3.1.1-SNAPSHOT+Travis-b1843.git-8c61372fdd, all the same

**Comment by TheE** [comment]
Could you try using the MySQL driver like so `url: jdbc:mysql://localhost/`?

As far as I know, Spigot does not bundle a separated driver for MariaDB. The MySQL driver should work fine however.

**Comment by ArtNRG** [comment]
The MySQL driver is working, thank you.  Adding some info about it in the wiki will be a good idea in my opinion.

**Comment by TheE** [comment]
> Adding some info about it in the wiki will be a good idea in my opinion.

[Done](https://github.com/MyWarp/MyWarp/wiki/Warp-Storage#jdbc-connection-urls). It was mentioned there before, too, but now it is clearly visible. 😄
