### ISSUE TITLE
Can we add player name as warp name?

### ISSUE THREAD

**Issue by scorninpc** [MyWarp/MyWarp#244]
I need add one warp per player, and want add player name as warp name. All player will get only one warp with her name. Can we configure that?

**Comment by TheE** [comment]
No, it is not possible to constrain warp names. Back in the days, I would have advised you to use MyWarp's sister plugin [MyHome](https://dev.bukkit.org/projects/myhome), but it does not appear to be supported anymore.

With MyWarp, the best you could do is the following:
- use [limits](https://github.com/MyWarp/MyWarp/wiki/Creation-Limits) to limit every player to one warp;
- do **not** grant you players access to the `warp remove` and `warp give` commands;
- manually create one warp per player based on her name;
- change the ownership of this warp to the player using `mw give -df <player> <warpname> this warp the player.

(If you use some sort of scripting plugin, you might be able to automate the last two steps somewhat by executing `warp create` when the player logs in for the first time. Unfortunately, I have no experience which scripting plugins so I cannot help you here.)
