### ISSUE TITLE
Error Messages

### ISSUE THREAD

**Issue by voigtman** [MyWarp/MyWarp#249]
This is a 2 part issue :
Part 1: **Error Message Configuration or permissions to see**
I'd like to be able to configure my own error messages or at least disable players from them. We don't use a vault economy so I've created a friendly interface for my players to use mywarp restricting warp creations with another kind of earned credit. Through this interface I restrict access to all of the mywarp root commands /warp /mywarp /mw /to and temporarily allow permissions to use them in the instant before the command is issued. I don't need, nor want, my players to see the root command prior to an error message as it adds confusion as my interface issues its own error messages. Also several of the error messages are highly technical in nature - especially for kids who are just learning the game.  Even if these cannot be configurable, a permission to disable seeing these errors would be ideal.

Part 2: **Error Message assumes player's gender**
When trying to give a player a warp and they're not online the system issues this message:
_Could not find a player named ' some player name '. Is she online?_ 

Instead it should say: 
_Could not find a player named ' some player name '. Are they online?_

**Comment by TheE** [comment]
> Part 1: **Error Message Configuration or permissions to see**

You can overwrite all of MyWarp's messages, see [here](https://github.com/MyWarp/MyWarp/wiki/Localizations#using-custom-localisations).

> Part 2: **Error Message assumes player's gender**

There does not appear to be any [consensus](https://english.stackexchange.com/questions/108457/is-using-she-when-the-gender-is-unknown-ungrammatical#108465) on which pronoun to use if the gender is not known or unspecified. I am used to reading "she" in such contexts, but apparently "they" is is also widely used.

I am going to change the sentence accordingly. In the meantime, you can easily overwrite it as described above.

**Comment by voigtman** [comment]
I apologize for the delayed response, thank you very much for the assistance! I wasn't aware it had even MORE customizations! What a great plugin you have here. thank you so much!
