### ISSUE TITLE
[FEATURE] Add warp’s GUI

### ISSUE THREAD

**Issue by danechek** [MyWarp/MyWarp#307]
The name speaks for itself.  I would like a menu where each player can see a list of his own or available to him warps, and the admin is a list of all warps or individual players, for example.

**Comment by TheE** [comment]
I hope that some kind of GUI can be added using chat components (essentially clickable words within the chat), see #210.  For example, every warp within the output of `/warp list` would be usable with a single click.

I will not be adding item or inventory-based GUIs, as long as there is no official API. Too much can go wrong here. hence, I am closing this ticket in favour of #210.
