### ISSUE TITLE
[FEATURE] BlueMap/pl3xmap hook

### ISSUE THREAD

**Issue by danechek** [MyWarp/MyWarp#313]
In cfg, you can enable hook to Dynmap, but will there be BlueMap and pl3xmap?

**Comment by danechek** [comment]
#https://github.com/pl3xgaming/Pl3xMap/issues/18

**Comment by danechek** [comment]
https://github.com/pl3xgaming/Pl3xMap/issues/18

**Comment by TheE** [comment]
It is unlikely that I'll add support for those. Pl3xmap is, according to their own site, not ready for production. BlueMap looks interesting, but seems to have fewer users than Dynmap.

However, if anybody really needs this functionality, I am open for PRs. Implementing support should be rather trivial, just look at the [`DynmapMarker`](https://github.com/MyWarp/MyWarp/blob/master/mywarp-bukkit/src/main/java/io/github/mywarp/mywarp/bukkit/DynmapMarker.java) class.
