### ISSUE TITLE
SLF4J error with Paper 1.17

### ISSUE THREAD

**Issue by sean-skt** [MyWarp/MyWarp#330]
MyWarp plugin fails to load on startup of Minecraft 1.17. When trying to warp, Minecraft issues a "auto tab completion" error when typing in a warp destination in game.

The log shows the following errors associated with this plugin on startup:

```
Console	: [0 12:44:18 WARN]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
Console	: [0 12:44:18 WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation
Console	: [0 12:44:18 WARN]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Console	: [0 12:44:18 INFO]: [MyWarp] Loading MyWarp v3.1.2-SNAPSHOT+GitHub_Action-b92.git-066e08c094
Console	: [0 12:44:43 INFO]: [MyWarp] Enabling MyWarp v3.1.2-SNAPSHOT+GitHub_Action-b92.git-066e08c094
Console	: [0 12:44:46 INFO]: [io.github.mywarp.mywarp.internal.flyway.core.internal.license.VersionPrinter] Flyway Community Edition 7.10.0 by Redgate
Console	: [0 12:44:46 INFO]: [MyWarp] Disabling MyWarp v3.1.2-SNAPSHOT+GitHub_Action-b92.git-066e08c094
```

Using Paper b30 for Minecraft 1.17. Getting the above errors with builds 90 and 92 of MyWarp plugin.
Using with Java 16.0.1 on Ubuntu 18.04.

mywarp-bukkit-3.1.1-all.jar does work fine in Paper 1.17. But on occasion has caused a Minecraft Server restart with the following:
```
Console	: [0 12:14:06 INFO]: [MyWarp] [m63 warps loaded.[m
Notice	: Minecraft server has stopped running.
Warning : Server was not yet ready, automatically restarting (Attempt: 1 of 5)
```

Not 100% sure if MyWarp is the issue but any restart always seemed to occur after loading warps from MySQL database.

**Comment by TheE** [comment]
Thanks for letting me know. I am investigating the issue. Until I am able to resolve this, please stick to 3.1.1 which seems to work fine on 1.17.

Some observations:
- The issues also affect 1.16 (and likely older versions, too).
- The crash seems to have been introduced by updating FlyWay from 7.8.1 to 7.8.2 in 1f7eb77. Build [67](https://mywarp.github.io/builds/67.html) and older work fine, while newer builds crash.
- Even for builds that seem to work, logging seems to be broken (`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"`). This does not affect 3.1.1 so may have been introduced later.

**Comment by TheE** [comment]
Both issues should be fixed in the latest development build. 😄

**Comment by sean-skt** [comment]
Awesome. Thanks so much. Now that's service!! :D
