### ISSUE TITLE
[QUESTION] Permission for the /to <warp> command

### ISSUE THREAD

**Issue by Veerplays** [MyWarp/MyWarp#351]
### Question

how to give permission to use the /to (name) when ever my friends use it, it says insufficient permission they are not opped pls pls help

**Comment by TheE** [comment]
The `/to <warp>` command requires the `mywarp.cmd.to` permission. A list of all command permissions can be found [here](https://github.com/MyWarp/MyWarp/wiki/Command-Reference#usage-commands).

Note that in addition your friends need to be able to access the <warp>, i.e. that warp needs to be **public** (`/warp public <warp>`) or they need to be **invited** (`/warp invite <player> <warp>) as described [here](https://github.com/MyWarp/MyWarp/wiki/Introduction#public-and-private-warps).
