### ISSUE TITLE
What does the override perm do?

### ISSUE THREAD

**Issue by nutellap** [MyWarp/MyWarp#355]
I've noticed the mywarp.override.* permission was set to true and I'm not sure what it means. I looked on the wiki and couldn't find anything that described what it does. 

Thank you in advance.

**Comment by TheE** [comment]
These permissions allow you to overwrite who may view, use and modify warps:
- By default, a player can only view and use the warps that are either public, created by her, or she is invited to. If she has the `mywarp.overwrite.view` permission, she can view all warps.
- With the `mywarp.overwrite.use` permission, a player can use all warps and not just those that are public, created by her or she is invited to.
- With the `mywarp.overwrite.modify` permission, a player can modify (update, delete…) all warps and not just those that were created by her. 
- You can set all of these permissions via `mywarp.overwrite.*`

I guess on most servers you want your admins to have the `mywarp.overwrite.*`permissions, while other players have none of these.
