### ISSUE TITLE
Config option to only show a player their warps & public warps. 

### ISSUE THREAD

**Issue by datsme** [MyWarp/MyWarp#357]
It is frustrating when looking for a warp you made and you have to scroll through eight or nine pages of warps listing that is not even yours. It also has the potential of giving away a secret location by name a player didn't want known. 

It would be extremely helpful and clean up the screen if there was a config or permissions option that removes warps that either do not belong to that player or are not public warps.
Perhaps even make the command sort and display something like...
Your warps:
Public Warps:
NOTE: It might even be easier to make this a permissions option so players with a higher trust level on the server can choose what/how they would like to see them listed.

**Comment by TheE** [comment]
Are you aware of the `/warp assets` or `/warp assets <player>` command?

You can also use filters in the `list` command:
> Use [-c] to only display warps with a creator whose name matches the given one. Use [-n] to only display warps whose name matches the given one. Use [-o] to change the ordering of results (see [here](https://github.com/MyWarp/MyWarp/wiki/Configuration-Reference#general-settings)). Use [-r] to only display warps located within that radius from your current position. Use [-w] to only display warps located on a world whose name matches the given one.

**Comment by datsme** [comment]
> Are you aware of the `/warp assets` or `/warp assets <player>` command?
> 
> You can also use filters in the `list` command:
> 
> > Use [-c] to only display warps with a creator whose name matches the given one. Use [-n] to only display warps whose name matches the given one. Use [-o] to change the ordering of results (see [here](https://github.com/MyWarp/MyWarp/wiki/Configuration-Reference#general-settings)). Use [-r] to only display warps located within that radius from your current position. Use [-w] to only display warps located on a world whose name matches the given one.

I feel so stupid! I am so sorry for requesting a feature that is already included!!! Thank you.

**Comment by TheE** [comment]
> Is there a way to prevent players from seeing other peoples warps?

What you could do is prevent them from using `/warp list` by **not** granting them the `mywarp.cmd.list` permission. Instead, grand them the `mywarp.cmd.assets.self` permission, which allows them to use `/warp assets` for themselves only.
