### ISSUE TITLE
Option to disable warps with the same name but with a other uppercrase/lowercase form

### ISSUE THREAD

**Issue by Blockbude** [MyWarp/MyWarp#42]
Players can create different warps based on the uppercase and lowercase of letters:

WarpTest is different warp than warptest 

A option to disable this would be pretty nice.

**Comment by TheE** [comment]
Yes, I am going to implement an option for case insensitive warp names at some point.

**Comment by kelseypolo** [comment]
Is there an update on this feature? We would really like the option to disable case insensitive warp names.

**Comment by TheE** [comment]
Duplicate of #142.
