### ISSUE TITLE
[Bug] , in economy value

### ISSUE THREAD

**Issue by moda84** [MyWarp/MyWarp#428]
### Description of the Problem
Invalid symbol replace ,
How fix it?
![image](https://user-images.githubusercontent.com/44532692/164927008-d5260a85-ad1e-4b72-bc18-c9d773475c11.png)

### Log Output

```
<!-- If appreciable, past the log that shows the error -->
```

### Affected Version
* MyWarp: `<!-- Output of /version MyWarp -->`
3.1.2-SNAPSHOT+GitHub_Action-b183.git-7e0b9b40e0

* Minecraft and Bukkit Implementation: `<!-- Output of /version -->`
Current: git-Purpur-1612 (MC: 1.18.2)*
Previous: git-Purpur-1609 (MC: 1.18.2)

**Comment by TheE** [comment]
What language is your client using?

**Comment by moda84** [comment]
> What language is your client using?
Russian

**Comment by TheE** [comment]
I cannot reproduce the issue using the latest development build, probably it has already been fixed in the translations.
