### ISSUE TITLE
Players can't use social commands [QUESTION]

### ISSUE THREAD

**Issue by lukeptyler** [MyWarp/MyWarp#493]
I have LuckyPerms, and have set the following in the default group:
`mywarp.cmd.public`
`mywarp.cmd.private`
`mywarp.cmd.give`
but when any non-op player tries to use one of those commands they get the "insufficient permissions" error message. 

All other commands I have given permission for work fine, and these are the only social commands I have set permission for. Am I doing something wrong?

**Comment by TheE** [comment]
No, if you grant these permissions, players should be able to use the `/warp private`, `/warp public` and `/warp give` commands. I have just tested this and can confirm that it works as intended.

Are you sure that there is no error with how permissions and groups are setup in LuckyPerms? Have you tried to grant a specific player the mentioned permissions directly (i.e. not via group inheritance)? If this works, it is likely that there is an error within your LuckyPerms setup.
