### ISSUE TITLE
Add a configuration option to specify which warps are shown on Dynmap

### ISSUE THREAD

**Issue by epicbastion** [MyWarp/MyWarp#63]
Is there anyway in your next release you could add a config option to allow all or no private warps to be shown on dynmap?  I think as of now only public warps show on dynmap.

**Comment by TheE** [comment]
Do you have a certain use-case in mind where private warps should be visible to the public?

I did not implement this function until now because I did not see that it might be needed. After all, private warps are supposed to be private: e.g. I have a warp called `e_diamonds` that marks a spot where I have found some diamonds and need to come back with an enchanted tool later. If this spot where openly visible, others could simply walk there and mine the diamonds.

**Comment by epicbastion** [comment]
in my case, an adventure server, in order to control warping across the server i have to set all warps to private, I am the guy who asked about individual warp perms on bukkit a couple days ago.  Any way, since all warps are private they don't show up on the dynmaps for either my build or test servers.

long story short, if i could turn on private warps in the config it would help me out.

**Comment by epicbastion** [comment]
If you would be so kind to just tell me what to remove from the DynmapMarkers.java file to allow all warps to show i will compile it myself, I just can not seem to figure out what to change to show all warps.

Thanks.

**Comment by TheE** [comment]
You should be able to replace the `DynmapMarkers.java` file with [this](https://gist.github.com/TheE/c7e28db0481687e0e8b3) one (note the changes should work, but are untested).

Sorry, I am currently extremely busy and cannot work on MyWarp, except perhaps for critical bugs. I will keep this change in mind though. Maybe I can hook in Dynmap's user system and display private warps only to users that can access them...

**Comment by epicbastion** [comment]
Thanks for your help i will not trouble you further.  using dynmaps perms would be a solution to add mapping for private warps. for an individual player.

**Comment by epicbastion** [comment]
ya that didnt work so ya.

does it have to do with these lines

private void addMarker(Warp warp) {
    if (!warp.isType(Warp.Type.PUBLIC)) {
      return;

**Comment by TheE** [comment]
Yes. I altered the gist shortly after writing the comment, probably you still got the old version. Could you try again using the updated one?

**Comment by epicbastion** [comment]
ya that didnt work, i created a public test warp to make sure there was nothing else wrong with my configuration and it shows up. there is just the one page that deals with dynmap in the bukkit part of the source code so ya, dont know, thanks for trying though.

**Comment by TheE** [comment]
Wait, so you wanted to display private *but no* public warps?

**Comment by epicbastion** [comment]
no, i want to display all warps.

**Comment by epicbastion** [comment]
i have all my warps set to private so i created a public one to make sure i hadnt screwed something else up that was preventing the private ones from showing up.

**Comment by TheE** [comment]
Once #74 is implemented, I will will allow users to configure precisely witch warps to display on Dynmap via a config-option that uses the search language. This should cover all possible usage scenarios.

**Comment by datsme** [comment]
I know this is an old post however, I would also like to upvote this feature request.
In my case Players do not have access to the world Dynmap URL only the admin can view it. Having the ability to see all the warp locations on dynmap would be beneficial to us.

**Comment by TheE** [comment]
I have just added this function. You can try it using the latest development build.

In MyWarp's `config.yml`, there is a new setting `dynmap.showTypes`. MyWarp will push all warps with a type present in the list to Dynmap. By default, only public warps are shown. To display all warps, add `private` to the list:

```YAML
   showTypes:
     - public
     - private
```
